eticaret/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path("", views.index, name= "home"),
    path("category/<slug:slug>", views.urunler, name= "urunler"),
    path("urun/<slug:slug>", views.urun_detay, name="urun_detay"),
    path("search_product", views.search_product, name= "search_product"),
    #####account
    path("login", views.login_request, name= "login"),
    path("register", views.register_request, name= "register"),
    path("logout", views.logout_request, name= "logout"),
    #####favoriler
    path("favoriler", views.favoriler, name= "favoriler"),
    path('favorilere_ekle/<int:id>', views.favorilere_ekle, name='favorilere_ekle'),
    path('favorilerden_sil/<int:id>', views.favorilerden_sil, name='favorilerden_sil'),
    path('favorilere_eklenen_urunler_kategori/', views.favorilere_eklenen_urunler_kategori, name='favorilere_eklenen_urunler_kategori'),
    #####Sepet
    path("sepet", views.sepet, name= "sepet"),
    path('sepete_ekle/<int:id>', views.sepete_ekle, name='sepete_ekle'),
    path('sepetten_sil/<int:id>', views.sepetten_sil, name='sepetten_sil'),
    #####Profil
    path("profile", views.profile, name= "profile"),
    path('profile_sil/<int:id>', views.profile_sil, name='profile_sil'),
    path('profile_email_guncelle', views.profile_email_guncelle, name='profile_email_guncelle'),
    path('password/', views.user_password, name='user_password'),
    #######Adres
    path('add_address', views.add_address, name='add_address'),
    path('address_list', views.address_list, name='address_list'),
    path('delete_address/<int:address_id>', views.delete_address, name='delete_address'),
    #######Credit-Card
    path('add_credit_card/', views.add_credit_card, name='add_credit_card'),
    path('credit_card_list/', views.credit_card_list, name='credit_card_list'),
    path('delete_credit_card/<int:credit_card_id>/', views.delete_credit_card, name='delete_credit_card'),
    #######Siparis
    path('siparis/', views.siparis, name='siparis'),
    path('siparislerim/', views.siparislerim, name='siparislerim'),
    path('siparis_detay/<int:id>', views.siparis_detay, name='siparis_detay'),
    #######Yorum
    path('yorum_ekle/<int:urun_id>/', views.yorum_ekle, name='yorum_ekle'),
    path('yorumlar', views.yorumlar, name='yorumlar'),
    path('yorum_sil/<int:id>', views.yorum_sil, name='yorum_sil'),
]

main/models.py
from django.db import models
from django.forms import ModelForm
from django.utils.text import slugify
from djmoney.models.fields import MoneyField
from django.contrib.auth.models import User
from django.apps import apps

# Create your models here.

#TEMA -> temaId, temaAdı, ...

class Renk(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return f"{self.name}"

class Beden(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return f"{self.name}"

class Tema(models.Model):
    name = models.CharField(max_length=150)
    slug = models.SlugField(null=False, blank=True, unique=True, db_index=True,editable=False)
    def __str__(self):
        return f"{self.name}"
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

#CATEGORY -> categoryId, temaId, categoryAdı,..
class Category(models.Model):
    name = models.CharField(max_length=150)
    slug = models.SlugField(null=False, blank=True, unique=True, db_index=True,editable=False)
    tema = models.ForeignKey(Tema, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.name}"
    def save(self, *args, **kwargs):
         self.slug = slugify(self.name)
         super().save(*args, **kwargs)




class Urun(models.Model):
    tema = models.ForeignKey(Tema, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    renk = models.ForeignKey(Renk, on_delete=models.CASCADE)
    beden = models.ForeignKey(Beden, on_delete=models.CASCADE)
    aciklama = models.TextField(blank=True)
    name = models.CharField(max_length=200)
    slug = models.SlugField(null=False, blank=True, unique=True, db_index=True,editable=False)
    available = models.BooleanField(default=True)
    stok = models.PositiveIntegerField()
    fiyat = MoneyField(max_digits=10, default_currency='TL')
    barkod = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return f"{self.name}"
    def save(self, *args, **kwargs):
         self.slug = slugify(self.name)
         super().save(*args, **kwargs)

    @property
    def get_images(self):
        return self.images.all()

        

class UrunFotograf(models.Model):
    urun = models.ForeignKey(Urun, on_delete=models.CASCADE, default= 1, related_name='images')
    image = models.ImageField(upload_to="urunler")


class Sepet(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    urun = models.ForeignKey(Urun, on_delete= models.SET_NULL, null=True)
    miktar = models.IntegerField()

    @property
    def amount(self):
        return(self.miktar * self.urun.fiyat)

    @property
    def fiyat(self):
        return (self.urun.fiyat)




class Sehirler(models.Model):
    sehir_adi = models.CharField(max_length=50)
    def __str__(self):
        return self.sehir_adi


class Adres(models.Model):
    adres_adi = models.CharField(max_length=50)
    adres = models.TextField(max_length=400)
    sehir = models.ForeignKey(Sehirler, on_delete=models.CASCADE, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.adres_adi

    @property
    def username(self):
        return(self.user.username)
    
    @property
    def sehir_adi(self):
        return(self.sehir.sehir_adi)

class Favoriler(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    urun = models.ForeignKey(Urun, on_delete=models.CASCADE, default= 1)


class CreditCard(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    card_number = models.CharField(max_length=16)
    expiration_date_month = models.CharField(max_length=2 ,default=1)
    expiration_date_year = models.CharField(max_length=2, default=24)
    cvv = models.CharField(max_length=3)
    def __str__(self):
        return self.card_number

DURUM_CHOICES = (
    ('onay_bekliyor', 'Onay Bekliyor'),
    ('kargolandi', 'Kargolandı'),
    ('teslim_edildi', 'Teslim Edildi'),
    ('iade_edildi', 'İade Edildi'),
)

class Siparis(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=10, default='no-name')
    last_name = models.CharField(max_length=10, default='no-name')
    telefon = models.CharField(blank=True, max_length=20)
    urunler = models.ManyToManyField(Urun, through='SiparisUrun')
    adres = models.ForeignKey(Adres, on_delete=models.CASCADE)
    kredi_karti = models.ForeignKey(CreditCard, on_delete=models.CASCADE)
    tarih = models.DateTimeField(auto_now_add=True)
    ip = models.CharField(blank=True, max_length=20)
    durum = models.CharField(max_length=50, choices=DURUM_CHOICES, default='onay_bekliyor')
    toplam_tutar = MoneyField(max_digits=10, default_currency='TL')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

STATUS = (
        ('hazirlaniyor', 'hazirlaniyor'),
        ('teslim_edildi', 'teslim_edildi'),
    )

class SiparisUrun(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    siparis = models.ForeignKey(Siparis, on_delete=models.CASCADE)
    urun = models.ForeignKey(Urun, on_delete=models.CASCADE)
    miktar = models.PositiveIntegerField()
    fiyat = MoneyField(max_digits=10, default_currency='TL')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



class Yorum(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    yorum_urun = models.ForeignKey(Urun, on_delete=models.CASCADE, default= 1)
    text = models.TextField(max_length=300)
    image = models.ImageField(upload_to='yorumlar', null=True)
    create_at=models.DateTimeField(auto_now_add=True,null=True)
    update_at=models.DateTimeField(auto_now=True, null=True)

    @property
    def urun_adi(self):
        return(self.yorum_urun.name)
    
    @property
    def username(self):
        return(self.user.username)

main/forms.py
from django.contrib.auth.forms import  UserChangeForm
from django.contrib.auth.models import User
from django.forms import EmailInput,ModelForm
from main.models import Sepet, Adres, CreditCard, Siparis, Yorum


class SepetForm(ModelForm):
    class Meta:
        model = Sepet
        fields = ['miktar']


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email',)
        widgets = {
            'email'     : EmailInput(attrs={'class': 'input','placeholder':'email'}),
        }

class AddressForm(ModelForm):
    class Meta:
        model = Adres
        fields = ['adres_adi', 'adres', 'sehir']

class CreditCardForm(ModelForm):
    class Meta:
        model = CreditCard
        fields = ['card_number', 'expiration_date_month','expiration_date_year', 'cvv']


class SiparisForm(ModelForm):
    class Meta:
        model = Siparis
        fields = ['first_name','last_name','telefon','adres','kredi_karti']


class YorumForm(ModelForm):
    class Meta:
        model = Yorum
        fields = ['text', 'image']

main/templates/add_address.html
{% extends 'base.html' %}


{% block title %}
    Adres
{% endblock %}



{% block content %}

<form method="post" class="form-horizontal">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>
</form>

{% endblock %}

main/templates/address_list.html
{% extends 'base.html' %}


{% block title %}
    Adres
{% endblock %}



{% block content %}

<table class="table">
    <thead>
        <tr>
            <th>Adres Adı</th>
            <th>Adres</th>
            <th>Şehir</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for address in addresses %}
            <tr>
                <td>{{ address.adres_adi }}</td>
                <td>{{ address.adres }}</td>
                <td>{{ address.sehir }}</td>
                <td>
                    <a href="{% url 'delete_address' address.id %}" class="btn btn-danger btn-sm">Delete</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<button class="btn btn-outline-primary" type="submit"> <a class="dropdown-item" href="{% url 'add_address' %}"><h5>Adres Ekle</h5></a> </button>

{% endblock %}

main/templates/favoriler.html
{% extends 'base.html' %}


{% block style %}
.card-img-tiles {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  position: relative;
  background-color: #fff;
  z-index: 5
}

.card-img-tiles .main-img>img,
.card-img-tiles .thumblist>img {
    display: block;
    width: 100%
}
.card-img-tiles .main-img {
  width: 67%;
  padding-right: .375rem
}

.card-img-tiles .thumblist {
  width: 33%;
  padding-left: .375rem
}

.card-img-tiles .thumblist>img {
  margin-bottom: .75rem
}

.card-img-tiles .thumblist>img:last-child {
  margin-bottom: 0
}

.mb-grid-gutter {
  margin-bottom: 30px !important;
}

{% endblock %}

{% block title %}

    Home

{% endblock %}



{% block content %}

{% if messages %}

<ul class="messages">
  {% for message in messages  %}
  <div class="alert alert-primary" role="alert">
    {{message}}
  </div>
  {% endfor %}
</ul>

{% endif %}
<h1>Favoriler</h1>

<div class="container pb-5 mb-sm-1">
    <div class="row">
  {% for favori in favoriler %}
  
  
        <div class="col-md-4 col-sm-6">
            <div class="card border-0 mb-grid-gutter">
                  <a class="card-img-tiles" href="{% url 'urun_detay' favori.urun.slug %}">
                    {% for image in  favori.urun.get_images|slice:":3" %}
                    {% if forloop.first %}
                    <div class="main-img"><img src="{{ image.image.url }}" alt=""></div>
                    {% else %}
                    <div class="thumblist"><img src="{{ image.image.url }}" alt=""></div>
                    {% endif %}
                    {% endfor %}
                  </a>
                  <div class="card-body border mt-n1 py-4 text-center">
                    <h2 class="h5 mb-1">{{favori.urun.name}}</h2>
                    <span class="d-block mb-3 font-size-xs text-muted"><span class="font-weight-semibold">{{favori.urun.fiyat}}</span></span>
                    <a href="/favorilerden_sil/{{favori.id}}" onclick ="return confirm('Silmek istediğinizden emin misiniz?')"><input type="submit" value="Sil" class="btn btn-primary"></a>
                  </div>  
            </div>
        </div>
  
  
  
  {% endfor %}
  </div>
  </div>

{% endblock %}

main/templates/index.html
{% extends 'base.html' %}


{% block title %}

    Hoşgeldiniz

{% endblock %}



{% block content %}

{% if error %} <div class="alert alert-danger"> {{error}}</div> {% endif %}




HOŞGELDİNİZ

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}


{% block title %}

    Login
{% endblock %}



{% block content %}

<div class="container mt-3">
    <div class="col">
        <h1>Login</h1>
        <hr>
        <form method="POST">
            {% csrf_token %}
            {% if error %} <div class="alert alert-danger"> {{error}}</div> {% endif %}
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" name="username">
            </div>
            <div class="mb-3">
                <label for="username" class="form-label">Password</label>
                <input type="password" class="form-control" name="password">
            </div>

            <input type="submit" value="Login" class="btn btn-primary">
        </form>
    </div>
</div>




{% endblock %}

main/templates/profile.html
{% extends 'base.html' %}


{% block title %}

    Profile
{% endblock %}



{% block content %}

{% if messages %}
        {% for message in messages %}
            <div style="color: #d43f3a; font-size: medium">
                {{ message|safe }}
            </div>
        {% endfor %}
{% endif %}

<div class="container mt-3">
    <div class="col">
        <h1>Profilim</h1>
        <hr>
            <div class="mb-3">
                <h3>Kullanıcı Adı: {{ user.username }}</h3>
            </div>
            <div class="mb-3">
                <h3>e-Mail: {{ user.email }}</h3>
            </div>
            <div class="mb-3">
                <h3>Adı: {{ user.first_name }}</h3>
            </div>
            <div class="mb-3">
                <h3>Soyadı: {{ user.last_name }}</h3>
            </div>
            <a href="{% url 'credit_card_list' %}"><input type="submit" value="Kredi Kartlarım" class="btn btn-primary"></a><span>  </span><a href="/profile_email_guncelle"><input type="submit" value="Email Güncelle" class="btn btn-primary"></a> <a href="/profile_sil/{{user.id}}"><input type="submit" value="Hesabı Sil" class="btn btn-danger"></a> 
    </div>
</div>




{% endblock %}

main/templates/profile_parola_guncelle.html
{% extends 'base.html' %}


{% block title %}

    Profile
{% endblock %}



{% block content %}

<div class="col-md-9">
    <div class="billing-details">
        <div class="section-title">
            <h3 class="title">Parola Değiştir</h3>
        </div>
    </div>

    {% if messages %}
        {% for message in messages %}
            <div style="color: #d43f3a; font-size: medium">
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}


    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <button class="primary-btn" type="submit">Save changes</button>
    </form>

</div>




{% endblock %}

main/templates/register.html
{% extends 'base.html' %}


{% block title %}

Register
{% endblock %}



{% block content %}

<div class="container mt-3">
    <div class="col">
        <h1>Register</h1>
        <hr>
        <form method="POST">
            {% csrf_token %}
            {% if error %} <div class="alert alert-danger"> {{error}}</div> {% endif %}
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" name="username">
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="text" class="form-control" name="email">
            </div>
            <div class="row mb-3">
                <div class="col">
                    <label for="firstname" class="form-label">isim</label>
                    <input type="text" class="form-control" name="firstname">
                </div>
                <div class="col"> 
                    <label for="lastname" class="form-label">Soyisim</label>
                    <input type="text" class="form-control" name="lastname">
                </div>
            </div>
            <div class="row mb-3">
                <div class="col">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control" name="password">
                </div>
                <div class="col">
                    <label for="repassword" class="form-label">Re-Password</label>
                    <input type="password" class="form-control" name="repassword">
                </div>
            </div>
            <input type="submit" value="Register" class="btn btn-primary">
        </form>
    </div>
</div>

{% endblock %}

main/templates/siparis.html
{% extends 'base.html' %}

{% block style %}

body{margin-top:20px;}
select.form-control:not([size]):not([multiple]) {
    height: 44px;
}
select.form-control {
    padding-right: 38px;
    background-position: center right 17px;
    background-image: url(data:image/svg+xml;utf8;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iaXNv…9nPgo8Zz4KPC9nPgo8Zz4KPC9nPgo8Zz4KPC9nPgo8Zz4KPC9nPgo8Zz4KPC9nPgo8L3N2Zz4K);
    background-repeat: no-repeat;
    background-size: 9px 9px;
}
.form-control:not(textarea) {
    height: 44px;
}
.form-control {
    padding: 0 18px 3px;
    border: 1px solid #dbe2e8;
    border-radius: 22px;
    background-color: #fff;
    color: #606975;
    font-family: "Maven Pro",Helvetica,Arial,sans-serif;
    font-size: 14px;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
}

.shopping-cart,
.wishlist-table,
.order-table {
    margin-bottom: 20px
}

.shopping-cart .table,
.wishlist-table .table,
.order-table .table {
    margin-bottom: 0
}

.shopping-cart .btn,
.wishlist-table .btn,
.order-table .btn {
    margin: 0
}

.shopping-cart>table>thead>tr>th,
.shopping-cart>table>thead>tr>td,
.shopping-cart>table>tbody>tr>th,
.shopping-cart>table>tbody>tr>td,
.wishlist-table>table>thead>tr>th,
.wishlist-table>table>thead>tr>td,
.wishlist-table>table>tbody>tr>th,
.wishlist-table>table>tbody>tr>td,
.order-table>table>thead>tr>th,
.order-table>table>thead>tr>td,
.order-table>table>tbody>tr>th,
.order-table>table>tbody>tr>td {
    vertical-align: middle !important
}

.shopping-cart>table thead th,
.wishlist-table>table thead th,
.order-table>table thead th {
    padding-top: 17px;
    padding-bottom: 17px;
    border-width: 1px
}

.shopping-cart .remove-from-cart,
.wishlist-table .remove-from-cart,
.order-table .remove-from-cart {
    display: inline-block;
    color: #ff5252;
    font-size: 18px;
    line-height: 1;
    text-decoration: none
}

.shopping-cart .count-input,
.wishlist-table .count-input,
.order-table .count-input {
    display: inline-block;
    width: 100%;
    width: 86px
}

.shopping-cart .product-item,
.wishlist-table .product-item,
.order-table .product-item {
    display: table;
    width: 100%;
    min-width: 150px;
    margin-top: 5px;
    margin-bottom: 3px
}

.shopping-cart .product-item .product-thumb,
.shopping-cart .product-item .product-info,
.wishlist-table .product-item .product-thumb,
.wishlist-table .product-item .product-info,
.order-table .product-item .product-thumb,
.order-table .product-item .product-info {
    display: table-cell;
    vertical-align: top
}

.shopping-cart .product-item .product-thumb,
.wishlist-table .product-item .product-thumb,
.order-table .product-item .product-thumb {
    width: 130px;
    padding-right: 20px
}

.shopping-cart .product-item .product-thumb>img,
.wishlist-table .product-item .product-thumb>img,
.order-table .product-item .product-thumb>img {
    display: block;
    width: 100%
}

@media screen and (max-width: 860px) {
    .shopping-cart .product-item .product-thumb,
    .wishlist-table .product-item .product-thumb,
    .order-table .product-item .product-thumb {
        display: none
    }
}

.shopping-cart .product-item .product-info span,
.wishlist-table .product-item .product-info span,
.order-table .product-item .product-info span {
    display: block;
    font-size: 13px
}

.shopping-cart .product-item .product-info span>em,
.wishlist-table .product-item .product-info span>em,
.order-table .product-item .product-info span>em {
    font-weight: 500;
    font-style: normal
}

.shopping-cart .product-item .product-title,
.wishlist-table .product-item .product-title,
.order-table .product-item .product-title {
    margin-bottom: 6px;
    padding-top: 5px;
    font-size: 16px;
    font-weight: 500
}

.shopping-cart .product-item .product-title>a,
.wishlist-table .product-item .product-title>a,
.order-table .product-item .product-title>a {
    transition: color .3s;
    color: #374250;
    line-height: 1.5;
    text-decoration: none
}

.shopping-cart .product-item .product-title>a:hover,
.wishlist-table .product-item .product-title>a:hover,
.order-table .product-item .product-title>a:hover {
    color: #0da9ef
}

.shopping-cart .product-item .product-title small,
.wishlist-table .product-item .product-title small,
.order-table .product-item .product-title small {
    display: inline;
    margin-left: 6px;
    font-weight: 500
}

.wishlist-table .product-item .product-thumb {
    display: table-cell !important
}

@media screen and (max-width: 576px) {
    .wishlist-table .product-item .product-thumb {
        display: none !important
    }
}

.shopping-cart-footer {
    display: table;
    width: 100%;
    padding: 10px 0;
    border-top: 1px solid #e1e7ec
}

.shopping-cart-footer>.column {
    display: table-cell;
    padding: 5px 0;
    vertical-align: middle
}

.shopping-cart-footer>.column:last-child {
    text-align: right
}

.shopping-cart-footer>.column:last-child .btn {
    margin-right: 0;
    margin-left: 15px
}

@media (max-width: 768px) {
    .shopping-cart-footer>.column {
        display: block;
        width: 100%
    }
    .shopping-cart-footer>.column:last-child {
        text-align: center
    }
    .shopping-cart-footer>.column .btn {
        width: 100%;
        margin: 12px 0 !important
    }
}

.coupon-form .form-control {
    display: inline-block;
    width: 100%;
    max-width: 235px;
    margin-right: 12px;
}

.form-control-sm:not(textarea) {
    height: 36px;
}



{% endblock %}

{% block title %}

    Sepet
{% endblock %}



{% block content %}

{% if messages %}

<ul class="messages">
  {% for message in messages  %}
  <div class="alert alert-primary" role="alert">
    {{message}}
  </div>
  {% endfor %}
</ul>

{% endif %}

<div class="container padding-bottom-3x mb-1">
  <!-- Shopping Cart-->
  <div class="table-responsive shopping-cart">
      <table class="table">
          <thead>
              <tr>
                  <th>Ürün Adı</th>
                  <th class="text-center">Miktar</th>
                  <th class="text-center">Toplam Tutar</th>
              </tr>
          </thead>
          <tbody>
            {% for  rs in sepet  %}
              <tr>
                  <td>
                      <div class="product-item">
                          <a class="product-thumb" href="{% url 'urun_detay' rs.urun.slug %}"> 
                            {% for image in  rs.urun.get_images|slice:":1" %}
                            <img class="card-img" src="{{ image.image.url }}" alt="Card image cap">
                            {% endfor %}
                          </a>
                          <div class="product-info">
                              <h4 class="product-title"><a href="{% url 'urun_detay' rs.urun.slug %}">{{rs.urun.name}}</a></h4><span><em>Beden:</em> {{rs.urun.beden}}</span><span><em>Renk:</em> {{rs.urun.renk}}</span>
                          </div>
                      </div>
                  </td>
                  <td class="text-center">
                      <div class="count-input">
                        <p> {{rs.miktar}} </p>
                      </div>
                  </td>
                  <td class="text-center text-lg text-medium">{{rs.miktar}} * {{rs.fiyat}} = {{rs.amount}}</td>
              </tr>
              {% endfor  %}
          </tbody>
      </table>
  </div>
      <div class="column text-lg">Toplam: <span class="text-medium">{{total}}</span></div>
  </div>
  <div class="shopping-cart-footer">
      <div class="column"><a class="btn btn-success" href="#">Siparişi Tamamla</a></div>
  </div>

  <h5>Toplam tutar = {{total}}</h5>

  <form method="POST">
    {% csrf_token %}
    {% if error %} <div class="alert alert-danger"> {{error}}</div> {% endif %}
    {{ form.as_p }}
    {% comment %} <div class="mb-3">
        <label for="first_name">Ad:</label>
            <input type="text" name="first_name"  value="{{ user.first_name }}" class="input" maxlength="10" required id="first_name">
    </div>
    <div class="mb-3">
        <label for="last_name">Soyad</label>
        <input type="text" name="last_name"  value="{{ user.last_name }}" class="input" maxlength="10" required id="id_last_name">
    </div>
    <div class="row mb-3">
        <div class="col">
            <label for="telefon" class="form-label">Telefon</label>
            <input type="text" class="form-control" name="telefon">
        </div>
        <div class="col"> 
            <label for="lastname" class="form-label">Soyisim</label>
            <input type="text" class="form-control" name="lastname">
        </div>
    </div>
    <div class="row mb-3">
        <div class="col">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" name="password">
        </div>
        <div class="col">
            <label for="repassword" class="form-label">Re-Password</label>
            <input type="password" class="form-control" name="repassword">
        </div>
    </div>
    {% endcomment %}
    <div class="shopping-cart-footer">
        <input type="submit" value="Sipariş Ver" class="btn btn-primary">
    </div> 

</form>

{% endblock %}